// This file is auto-generated by @hey-api/openapi-ts

export type BinType = 'household_waste' | 'recycling' | 'garden_waste';

export type Body_login_access_token_api_v1_login_access_token_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type CollectionCreate = {
    bin_type: BinType;
    collection_date: string;
    notification_sent?: boolean;
};

export type CollectionPublic = {
    bin_type: BinType;
    collection_date: string;
    notification_sent?: boolean;
    id: string;
    user_id: string;
};

export type CollectionUpdate = {
    bin_type?: BinType | null;
    collection_date?: string | null;
    notification_sent?: boolean | null;
};

export type CollectionsPublic = {
    data: Array<CollectionPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type PreferredContactMethod = 'email' | 'sms';

export type ReminderTime = '1_hour' | '2_hours' | '12_hours' | '24_hours' | '48_hours';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserPublic = {
    name: string;
    email: string;
    phone_number?: string | null;
    preferred_contact_method?: PreferredContactMethod;
    address?: string;
    collection_url: string;
    reminder_time?: ReminderTime;
    is_active?: boolean;
    id: string;
    next_scrape_date: string;
};

export type UserRegister = {
    name: string;
    email: string;
    phone_number?: string | null;
    preferred_contact_method?: PreferredContactMethod;
    address?: string;
    collection_url?: string | null;
    reminder_time?: ReminderTime;
    is_active?: boolean;
    password: string;
};

export type UserUpdateMe = {
    name?: string | null;
    email?: string | null;
    phone_number?: string | null;
    preferred_contact_method?: PreferredContactMethod | null;
    address?: string | null;
    collection_url?: string | null;
    reminder_time?: ReminderTime | null;
    is_active?: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    formData: Body_login_access_token_api_v1_login_access_token_post;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = Token;

export type ReadUserMeApiV1UsersMeGetResponse = UserPublic;

export type DeleteUserMeApiV1UsersMeDeleteResponse = Message;

export type UpdateUserMeApiV1UsersMePatchData = {
    requestBody: UserUpdateMe;
};

export type UpdateUserMeApiV1UsersMePatchResponse = UserPublic;

export type UpdatePasswordMeApiV1UsersMePasswordPatchData = {
    requestBody: UpdatePassword;
};

export type UpdatePasswordMeApiV1UsersMePasswordPatchResponse = Message;

export type RegisterUserApiV1UsersSignupPostData = {
    requestBody: UserRegister;
};

export type RegisterUserApiV1UsersSignupPostResponse = UserPublic;

export type ReadUserByIdApiV1UsersUserIdGetData = {
    userId: string;
};

export type ReadUserByIdApiV1UsersUserIdGetResponse = UserPublic;

export type GetNextCollectionsApiV1CollectionsMeGetResponse = CollectionsPublic;

export type GetCollectionsApiV1CollectionsUserIdGetData = {
    userId: string;
};

export type GetCollectionsApiV1CollectionsUserIdGetResponse = CollectionsPublic;

export type GetCollectionApiV1CollectionsCollectionIdGetData = {
    collectionId: string;
};

export type GetCollectionApiV1CollectionsCollectionIdGetResponse = CollectionPublic;

export type UpdateCollectionApiV1CollectionsCollectionIdPatchData = {
    collectionId: string;
    requestBody: CollectionUpdate;
};

export type UpdateCollectionApiV1CollectionsCollectionIdPatchResponse = CollectionPublic;

export type DeleteCollectionApiV1CollectionsCollectionIdDeleteData = {
    collectionId: string;
};

export type DeleteCollectionApiV1CollectionsCollectionIdDeleteResponse = Message;

export type CreateCollectionApiV1CollectionsPostData = {
    requestBody: CollectionCreate;
};

export type CreateCollectionApiV1CollectionsPostResponse = CollectionPublic;